server:
  port: 9990

spring:
  application:
    name: dblab2_back
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mylab2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

# ??mybatis
mybatis:
  #  typeAliasesPackage: com.neuedu.entity
  mapper-locations: classpath*:com/yy/mapper/*.xml
